const students = [
  {
    fname: "John",
    lname: "Doe",
    class: "10A",
    Id: "E - 2345",
    motherName: "Jane Doe",
    fatherName: "Michael Doe",
    address: "123 Main St",
    gender: "Male",
    attendance: "absent",
    age: 16,
  },
  {
    fname: "Alice",
    lname: "Smith",
    class: "9B",
    Id: "E - 8724",
    motherName: "Mary Smith",
    fatherName: "David Smith",
    address: "456 Elm St",
    gender: "Female",
    attendance: "present",
    age: 15,
  },
  {
    fname: "Bob",
    lname: "Johnson",
    class: "11A",
    Id: "E - 1232",
    motherName: "Emily Johnson",
    fatherName: "Robert Johnson",
    address: "789 Oak St",
    gender: "Male",
    attendance: "present",
    age: 17,
  },
  {
    fname: "Sarah",
    lname: "Williams",
    class: "8C",
    Id: 4,
    motherName: "Linda Williams",
    fatherName: "Thomas Williams",
    address: "321 Pine St",
    gender: "Female",
    attendance: "present",
    age: 14,
  },
  {
    fname: "Michael",
    lname: "Brown",
    class: "12B",
    Id: 5,
    motherName: "Jennifer Brown",
    fatherName: "Christopher Brown",
    address: "987 Cedar St",
    gender: "Male",
    attendance: "present",
    age: 18,
  },
  {
    fname: "Emma",
    lname: "Miller",
    class: "10A",
    Id: 6,
    motherName: "Amy Miller",
    fatherName: "Richard Miller",
    address: "654 Birch St",
    gender: "Female",
    attendance: "absent",
    age: 16,
  },
  {
    fname: "James",
    lname: "Taylor",
    class: "9C",
    Id: 7,
    motherName: "Laura Taylor",
    fatherName: "Daniel Taylor",
    address: "789 Oak St",
    gender: "Male",
    attendance: "present",
    age: 15,
  },
  {
    fname: "Olivia",
    lname: "Anderson",
    class: "11B",
    Id: 8,
    motherName: "Jessica Anderson",
    fatherName: "Matthew Anderson",
    address: "543 Maple St",
    gender: "Female",
    attendance: "present",
    age: 17,
  },
  {
    fname: "Jacob",
    lname: "Thomas",
    class: "8A",
    Id: 9,
    motherName: "Melissa Thomas",
    fatherName: "Steven Thomas",
    address: "876 Walnut St",
    gender: "Male",
    attendance: "present",
    age: 14,
  },
  {
    fname: "Sophia",
    lname: "Garcia",
    class: "12C",
    Id: 10,
    motherName: "Maria Garcia",
    fatherName: "Jose Garcia",
    address: "234 Oak St",
    gender: "Female",
    attendance: "absent",
    age: 18,
  },
  {
    fname: "Sophia",
    lname: "Garcia",
    class: "12C",
    Id: 11,
    motherName: "Maria Garcia",
    fatherName: "Jose Garcia",
    address: "234 Oak St",
    gender: "Female",
    attendance: "present",
    age: 18,
  },
  {
    fname: "Sophia",
    lname: "Garcia",
    class: "12C",
    Id: 12,
    motherName: "Maria Garcia",
    fatherName: "Jose Garcia",
    address: "234 Oak St",
    gender: "Female",
    attendance: "present",
    age: 18,
  },
  {
    fname: "Sophia",
    lname: "Garcia",
    class: "12C",
    Id: 13,
    motherName: "Maria Garcia",
    fatherName: "Jose Garcia",
    address: "234 Oak St",
    gender: "Female",
    attendance: "present",
    age: 18,
  },
  {
    fname: "Sophia",
    lname: "Garcia",
    class: "12C",
    Id: 14,
    motherName: "Maria Garcia",
    fatherName: "Jose Garcia",
    address: "234 Oak St",
    gender: "Female",
    attendance: "present",
    age: 18,
  },
  {
    fname: "Sophia",
    lname: "Garcia",
    class: "12C",
    Id: 15,
    motherName: "Maria Garcia",
    fatherName: "Jose Garcia",
    address: "234 Oak St",
    gender: "Female",
    age: 18,
    attendance: "present",
  },
];

export default students;
